on: [push]
name: CI
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Minimal build
        run: cargo build --no-default-features
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build all
        run: cargo build
      - name: Test
        run: cargo test
