[package]
name = "rooibos-router"
version = "0.1.0"
edition = "2021"

[dependencies]
matchit = "0.8"
tachys = { git = "https://github.com/aschey/leptos", rev = "4ef9abc38fc9727f2f8e8d862791fc9169784c8c", features = [
  "reactive_graph",
  "tracing",
] }
url = "2"
reactive_graph = { version = "0.1.1", features = ["tracing", "effects"] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-reactive = { path = "../rooibos-reactive" }
rooibos-router-macros = { path = "../rooibos-router-macros" }
