[package]
name = "rooibos-router"
version = "0.1.0"
edition = "2021"

[dependencies]
matchit = "0.8"
tachys = { git = "https://github.com/leptos-rs/leptos", rev = "c5dea52e69fd1c1c83c0c089d1c73692ed2b4fea", features = [
    "reactive_graph",
] }
url = "2"
reactive_graph = { git = "https://github.com/leptos-rs/leptos", rev = "c5dea52e69fd1c1c83c0c089d1c73692ed2b4fea", features = [
    "tracing",
    "effects",
] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-router-macros = { path = "../rooibos-router-macros" }
