[package]
name = "rooibos-router"
version = "0.1.0"
edition = "2021"

[dependencies]
matchit = "0.8"
tachys = { git = "https://github.com/leptos-rs/leptos", rev = "a083b57260db4fa6588ff392bf24b4422047c0f6", features = [
    "reactive_graph",
    "tracing",
] }
url = "2"
reactive_graph = { git = "https://github.com/leptos-rs/leptos", rev = "a083b57260db4fa6588ff392bf24b4422047c0f6", features = [
    "tracing",
    "effects",
] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-router-macros = { path = "../rooibos-router-macros" }
