[package]
name = "rooibos-router"
version = "0.1.0"
edition = "2021"

[dependencies]
matchit = "0.8"
tachys = { git = "https://github.com/leptos-rs/leptos", rev = "73f0207a7d7002a5ca73b5bd578624abe17e0056", features = [
    "reactive_graph",
    "tracing",
] }
url = "2"
reactive_graph = { git = "https://github.com/leptos-rs/leptos", rev = "73f0207a7d7002a5ca73b5bd578624abe17e0056", features = [
    "tracing",
    "effects",
] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-router-macros = { path = "../rooibos-router-macros" }
