[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
futures-util = "0.3"
rooibos-dom = { path = "../rooibos-dom" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos", rev = "9fc2e7f55540fca383b7a7554a9fa9df3eca4e7f", features = [
    "tracing",
] }
any_spawner = { git = "https://github.com/leptos-rs/leptos", rev = "9fc2e7f55540fca383b7a7554a9fa9df3eca4e7f", features = [
    "tokio",
] }
tokio = { version = "1.37.0", default-features = false, features = [
    "sync",
    "macros",
    "rt-multi-thread",
] }
ratatui = { version = "0.26", default-features = false }
tap = "1"
tracing = "0.1"
termion = { version = "4", optional = true }

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm", "ratatui/crossterm"]
termion = ["dep:termion", "ratatui/termion"]
nightly = ["reactive_graph/nightly"]
