[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
futures-util = "0.3"
rooibos-dom = { path = "../rooibos-dom" }
reactive_graph = { path = "../../../leptos/reactive_graph", features = [
    "tracing",
    "effects",
] }
ratatui = { version = "0.27", default-features = false }
tap = "1"
tracing = "0.1"
derivative = "2"
termwiz = { version = "0.22.0", optional = true }
tokio-util = "0.7"
once_cell = "1"
wasm-compat = { git = "https://github.com/aschey/wasm-compat", rev = "34097fbe8e34cd1d5105b1a4aaf7c04822197422", features = [
    "all",
] }

[target.'cfg(unix)'.dependencies]
termion = { version = "4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.64"
any_spawner = { path = "../../../leptos/any_spawner", features = [
    "wasm-bindgen",
] }
tokio = { version = "1.38.0", default-features = false, features = [
    "sync",
    "macros",
    "rt",
] }
web-sys = { version = "0.3.64", features = ["console", "Window", "Document"] }
wasm-bindgen-futures = "0.4.37"
console_error_panic_hook = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
any_spawner = { path = "../../../leptos/any_spawner", features = ["tokio"] }
signal-hook = "0.3"
async-signal = "0.2"
tokio = { version = "1.38.0", default-features = false, features = [
    "sync",
    "macros",
    "time",
    "rt-multi-thread",
    "process",
] }

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm", "ratatui/crossterm"]
termion = ["dep:termion", "ratatui/termion"]
nightly = ["reactive_graph/nightly"]
termwiz = ["dep:termwiz", "ratatui/termwiz"]
