[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
futures-util = "0.3"
rooibos-dom = { path = "../rooibos-dom" }
rooibos-reactive = { path = "../rooibos-reactive" }
tokio = { version = "1.36.0", default-features = false, features = [
    "sync",
    "macros",
    "rt-multi-thread",
] }
ratatui = { path = "../../../ratatui", default-features = false }
dyn-clonable = "0.9"

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]
