[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
futures-util = "0.3"
rooibos-dom = { path = "../rooibos-dom" }
reactive_graph = { git = "https://github.com/leptos-rs/leptos", rev = "f34b9915c4dbda5ec871a60e6ea943283cad179a" }
any_spawner = { git = "https://github.com/leptos-rs/leptos", rev = "f34b9915c4dbda5ec871a60e6ea943283cad179a", features = [
    "tokio",
] }
tokio = { version = "1.37.0", default-features = false, features = [
    "sync",
    "macros",
    "rt-multi-thread",
] }
ratatui = { version = "0.26", default-features = false }

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm"]
