[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
futures-util = "0.3"
rooibos-dom = { path = "../rooibos-dom" }
reactive_graph = { path = "../../../leptos/reactive_graph", features = [
    "tracing",
    "effects",
] }
any_spawner = { path = "../../../leptos/any_spawner", features = ["tokio"] }
tokio = { version = "1.37.0", default-features = false, features = [
    "sync",
    "macros",
    "rt-multi-thread",
] }
ratatui = { version = "0.26", default-features = false }
tap = "1"
tracing = "0.1"
async-signal = "0.2"
signal-hook = "0.3"
derivative = "2"

[target.'cfg(unix)'.dependencies]
termion = { version = "4", optional = true }

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm", "ratatui/crossterm"]
termion = ["dep:termion", "ratatui/termion"]
nightly = ["reactive_graph/nightly"]
