[package]
name = "rooibos-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1"
crossterm = { version = "0.27", features = ["event-stream"], optional = true }
dyn-clonable = "0.9"
futures-cancel = { git = "https://github.com/aschey/futures-cancel", rev = "563f413a206c50c7cc1a003cf6a9d3b227b0b04d" }
futures-util = "0.3"
pin-project-lite = "0.2"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = "0.7"
tracing = "0.1"
rooibos-rsx = { path = "../rooibos-rsx" }
ratatui = { version = "0.24.0", default-features = false }
typed-builder = { version = "0.18" }
slotmap = "1"
once_cell = "1"
paste = "1"
rooibos-reactive = { path = "../rooibos-reactive" }


[features]
crossterm = ["dep:crossterm", "ratatui/crossterm"]
default = ["crossterm"]
