[package]
name = "rooibos-reactive-old"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1"
paste = "1"
rooibos-reactive-macros-old = { path = "../rooibos-reactive-macros-old" }
