[package]
name = "wasm-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
rooibos = { path = "../../crates/rooibos" }
tokio = { version = "1.37.0", features = ["rt", "macros"] }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"


[features]
nightly = ["rooibos/nightly"]
