mod catppuccin;
pub use catppuccin::*;
mod everforest;
pub use everforest::*;
mod gruvbox;
pub use gruvbox::*;
mod kanagawa;
pub use kanagawa::*;
mod monokai;
pub use monokai::*;
mod nord;
pub use nord::*;
mod one_dark;
pub use one_dark::*;
mod rose_pine;
pub use rose_pine::*;
mod solarized;
pub use solarized::*;
mod tailwind;
pub use tailwind::*;
mod tokyo_night;
pub use tokyo_night::*;
