[package]
name = "rooibos-reactive"
version = "0.1.0"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/leptos-rs/leptos"
description = "Reactive system for the Leptos web framework."

[dependencies]
slotmap = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde-lite = { version = "0.5", optional = true }
miniserde = { version = "0.1", optional = true }
futures = { version = "0.3" }
rustc-hash = "1"
serde_json = "1"
base64 = "0.21"
thiserror = "1"
tracing = "0.1"
cfg-if = "1"
indexmap = "2"
self_cell = "1"
pin-project = "1"
paste = "1"

[dev-dependencies]
log = "0.4"
tokio-test = "0.4"


[features]
default = []
serde = []
serde-lite = ["dep:serde-lite"]
miniserde = ["dep:miniserde"]
