[package]
name = "rooibos-xterm-js"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ratatui-xterm-js = { git = "https://github.com/aschey/ratatui-xterm-js", rev = "dfd38a462e16c63d781f521a2fdb463934bb7347" }
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3"
ratatui = { version = "0.27", default-features = false }
tokio = { version = "1.38.0", default-features = false, features = ["sync"] }
tracing = "0.1"
web-sys = { version = "0.3.64", features = ["console", "Window", "Document"] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-runtime = { path = "../rooibos-runtime" }
tap = "1"
