[package]
name = "rooibos-xterm-js"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ratatui-wasm = { path = "../../../ratatui-wasm" }
crossterm = { version = "0.27", features = ["event-stream"] }
futures = "0.3"
ratatui = { version = "0.26", default-features = false }
tokio = { version = "1.37.0", default-features = false, features = ["sync"] }
tracing = "0.1"
web-sys = { version = "0.3.64", features = ["console", "Window", "Document"] }
rooibos-dom = { path = "../rooibos-dom" }
rooibos-runtime = { path = "../rooibos-runtime" }
tap = "1"
