on: [push]
name: CI
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Run tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Minimal build
        run: cargo build --no-default-features
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Build all
        run: cargo build
      - name: Test
        run: cargo test
